### ISSUE TITLE
Can I use tss-lib to sign sequentially？

### ISSUE THREAD

**Issue by minchenzz** [binance-chain/tss-lib#102]
threshold = 2, full = 3
After signing by user A, the signing result is sent to user B, and user B completes the final signature.
Can tss-lib achieve this function?

**Comment by omershlo** [comment]
Yes, 
Once user B gets all the messages from the other party it has enough info to compute the signature and it can at that point compute it alone and not send its partial /full signature to the rest of the parties.
This probably require small modification to the code

**Comment by minchenzz** [comment]
@omershlo thank you.

I have another question: Must ```TestThreshold``` be equal to ```TestParticipants``` divided by two?

I got error when I set ```Threshold = 2```  ```Participants = 2 or 3```. 

```local_party_test.go:140:
                Error Trace:    local_party_test.go:140
                Error:          task signing, party {1,2}, round 9, culprits [{1,2}]: U doesn't equal T
                Test:           TestE2EConcurrent
```

**Comment by minchenzz** [comment]
@omershlo Thank you.

I have another question.

The number of secrets used for signing must be threshold+1?

https://github.com/binance-chain/tss-lib/blob/master/ecdsa/signing/local_party_test.go#L42

**Comment by omershlo** [comment]
Hi, 

1. Do you mean - what happens if you have more than threshold  +  1? how it is handled ? 
2. If you have threshold + 1 you can combine the secrets to form the ECDSA secret key, although I don't think it is implemented
