### ISSUE TITLE
tss-lib BIP-32 integration

### ISSUE THREAD

**Issue by HAOYUatHZ** [binance-chain/tss-lib#104]
# tss-lib BIP-32 integration

There are different cases in terms of integrating BIP-32 into tss-lib.

One is, we keep the keygen process as previous, but we can provide "path" when we are signing. The signature will be corresponding to the derived child key.

Another one is, we can derive the "child key_share"s from the "parent key_share"s, so that we can distribute the "child key_share"s to other people.

Here I would just briefly explain the first one as follows.

## Clarification
We omit the details of BIP32 and GG18 here. But since 

+ to derive hardened children keys, we will need to know the parent private key
+ in TSS use cases, we usually won't re-construct the full private key

So this document **only works for non-hardened derived keys**.

## Basic Idea
Let $G$ be the base point of the curve, $P$ be the parent public key, 

$I$ be as described in https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#private-parent-key--private-child-key,

$I_r$ is the right half of $I$, $I_l$ is the left half of $I$.

Then $I_r$ is the chaincode for each depth;

$I_l$, i.e, $\delta$, is the shift introducded by hierarchy levels, then

$$P_{child} = P + \delta * G$$

child private key: $$x_{child} = x + \delta = sum(u_i) + \delta$$

That means we will need one of the parties to change his $u_i$ to $u_i + \delta$. We call such a party as the leader.

Moreover, the VSS commitment to the polynomial should also be changed from

$$p(x) = a_0 + a_1 * x + a_2 * x^2 + ... + a_t * x^t \mod q$$

to

$$p'(x) = (a_0 + \delta) + a_1 * x + a_2 * x^2 + ... + a_t * x^t \mod q$$

## Implementation Example

Can refer to:

+ https://github.com/cryptochill/tss-ecdsa-cli
+ https://github.com/trepca/multi-party-ecdsa/tree/hd-support

As aforementioned, we would need a leader.

+ we can derive the derived_public_key from the master_public_key using path, see https://github.com/cryptochill/tss-ecdsa-cli/blob/master/src/common/hd_keys.rs, `f_l_new` is useful later
+ we will need to replace leader's VSS as in https://github.com/cryptochill/tss-ecdsa-cli/blob/master/src/common/signer.rs#L89-L118
+ we would need to update u_i and x_i for leader, but we only need to update x_i for non-leaders, as in https://github.com/cryptochill/tss-ecdsa-cli/blob/master/src/common/signer.rs#L123-L130
    * some of these values in binance's tss-lib are not stored permanently, but discarded after keygen. May need to make some changes and store them.

**Comment by kswlee** [comment]
@HAOYUatHZ hi, might you help comment this also applied to the case of EdDSA ?
