### ISSUE TITLE
does binance chain support multisig transaction natively?  

### ISSUE THREAD

**Issue by tpkeeper** [binance-chain/tss-lib#138]
does binance chain support multisig transaction natively?  or behave like multisig only through this tss lib?

**Comment by wanliqun** [comment]
nope to the best of my knowledge. BSC is a high definition fork of Ethereum, you can check how multisig works on it.

**Comment by yycen** [comment]
This repo is related to threshold signature. Multisig is a related technology but is out of scope of the repo. So I would like to close it.
