### ISSUE TITLE
可以提供一个在golang中使用的完整demo吗？

### ISSUE THREAD

**Issue by reydx** [binance-chain/tss-lib#152]
- 生成秘钥碎片
- 签名

**Comment by yycen** [comment]
你好，可以看看test case中的end to end example，例如[keygen](https://github.com/binance-chain/tss-lib/blob/681ebad57a16e6c291e37badf4b602a7cb4316f6/ecdsa/keygen/local_party_test.go#L169) 和[signing](https://github.com/binance-chain/tss-lib/blob/681ebad57a16e6c291e37badf4b602a7cb4316f6/ecdsa/signing/local_party_test.go#L37)

**Comment by reydx** [comment]
k，thank u
