### ISSUE TITLE
Can some parties be offline and the threshold singature still works?

### ISSUE THREAD

**Issue by arijitAD** [binance-chain/tss-lib#160]
Say I have 10 parties and 5 is the threshold. If 3 parties are offline can this still work?

**Comment by yycen** [comment]
Hello Arijit Das, yes if you mean work by signing. As your settings, any 6(5+1) subsets of the 10 parties could jointly do a signing. However for keygen, for at the end each party will have his own key share, they all needs to be online to finish.
