### ISSUE TITLE
add support for bip-32

### ISSUE THREAD

**Issue by HAOYUatHZ** [binance-chain/tss-lib#76]
currently this library doesn't support 
https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki key derivation directly

I understand that this lib only severs as the purpose of TSS, but it will be awesome if adding such a support
e.g.,
each party using their own derived secret can also perform  DKG & TSS 
and the consequent commitment corresponds to the derivation of the original commitment.

## Original scenario:
```
secrect A -------------------
                            |
secrect B --------------- keygen ------------- commitment X
                            |
secrect C -------------------
```

##  Derived:
```
child secrect A' ------------------
                                  |
child secrect B' --------------- keygen ------------- commitment X'
                                  |
child secrect C' ------------------
```

if A' & B' & C'   are derived from A, B, C respectively, using the same derivation path, the X' is expected as the derived from X using the same path.

**Comment by notatestuser** [comment]
Great suggestion, we have been looking into ways to do this

**Comment by HAOYUatHZ** [comment]
I have re-thought about it.

MPCed BIP-32 involving >2 signers actually requires a lot of computational complexity and thus become impracticable. Maybe we need to wait for a better protocol coming up.
