### ISSUE TITLE
May I ask a question about the key generation protocol?

### ISSUE THREAD

**Issue by yepp4you** [binance-chain/tss-lib#78]
4.1 Key generation protocol in GG18spec is as below.
  values Xi = g ^ xi are public.
But is the code only modulo?
round.save.Xi = new (big.Int) .Mod (xi, tss.EC (). Params (). N)

https://github.com/binance-chain/tss-lib/blob/1e5e2dd5ed1da5f0ad67665f0fedd08e555b00ff/ecdsa/keygen/round_3.go#L44

**Comment by notatestuser** [comment]
`round.save.Xi` is not public. What you're referring to (X_i = g ^ x_i) are known as `BigXi` in the code.
