### ISSUE TITLE
How to build the tss client?

### ISSUE THREAD

**Issue by flyq** [binance-chain/tss-lib#92]
I read the doc [here](https://docs.binance.org/tss.html),

and there are tss client:
```shell
./tss describe

> please set vault of this party:
[input vault name]
> Password to sign with this vault:
[input password]
address of this vault: bnb1
config of this vault:
```

And how should I do to get the tss?

**Comment by notatestuser** [comment]
The TSS CLI client is presently closed source.

**Comment by flyq** [comment]
> The TSS CLI client is presently closed source.

So how should I do to get the tss cli's executable program to run the demo?

**Comment by notatestuser** [comment]
Try this: https://github.com/binance-chain/node-binary/tree/master/cli/prod/0.6.2-TSS-0.1.2

**Comment by flyq** [comment]
> Try this: https://github.com/binance-chain/node-binary/tree/master/cli/prod/0.6.2-TSS-0.1.2

cool
