### ISSUE TITLE
PreParams generation time outs on machines with less than 3 CPU

### ISSUE THREAD

**Issue by nkuba** [binance-chain/tss-lib#93]
When running `GeneratePreParams` on machines with less than 3 CPUs the process timeouts as the generation goroutines are not being started.
It happens when `optionalConcurrency` is not provided so the `runtime.NumCPU()` is invoked, or when `optionalConcurrency` is less than `3`.

A number of concurrent execution is taken from `runtime.NumCPU()`:
https://github.com/binance-chain/tss-lib/blob/efd7f5ab41d31ade2dbc274371d07fb1b0dd2512/ecdsa/keygen/prepare.go#L39

Next, this value is divided by `3`, which gives us `0` and passed to generate functions:
https://github.com/binance-chain/tss-lib/blob/efd7f5ab41d31ade2dbc274371d07fb1b0dd2512/ecdsa/keygen/prepare.go#L51
https://github.com/binance-chain/tss-lib/blob/efd7f5ab41d31ade2dbc274371d07fb1b0dd2512/ecdsa/keygen/prepare.go#L65

As a result, prime generation routines are not started:
https://github.com/binance-chain/tss-lib/blob/efd7f5ab41d31ade2dbc274371d07fb1b0dd2512/common/safe_prime.go#L144-L149

**Comment by notatestuser** [comment]
Thank for this. We have always used devices with more than 2 cores and must have overlooked it.

Could you have a look at the fix in this commit? https://github.com/binance-chain/tss-lib/commit/15250acd920bbf169243cc0a9ec4eb92ba5ac57b

**Comment by nkuba** [comment]
Thanks for the fix!
